{% set name = "matplotx" %}
{% set version = "0.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matplotx-{{ version }}.tar.gz
  sha256: adf5c69fb4e57897730dc29156ea2e8598ae867f070f4b3bfe331f276948d7ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit-core
    - python >=3.7
    - matplotlib
  run:
    - matplotlib
    - networkx
    - python >=3.7

test:
  imports:
    - matplotx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/matplotx
  summary: Extensions for Matplotlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
