{% set name = "matplotx" %}
{% set version = "0.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matplotx-{{ version }}.tar.gz
  sha256: b931355d817c806278576aa540a6122f357d2381a59166a694f9f3f68b6e1823

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - networkx
    - python >=3.7

test:
  imports:
    - matplotx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/matplotx
  summary: Extensions for Matplotlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
