{% set name = "matplotx" %}
{% set version = "0.3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matplotx-{{ version }}.tar.gz
  sha256: b6926ce5274cf5da966cb46b90a8c7fefb761478c6c85c8f7ed3ee8ec90e86e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit-core
    - python >=3.7
    - matplotlib
  run:
    - matplotlib
    - networkx
    - python >=3.7

test:
  imports:
    - matplotx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/matplotx
  summary: Extensions for Matplotlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
