{% set name = "matplotx" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matplotx-{{ version }}.tar.gz
  sha256: 9a9b392d5ed44f5a8701e19061f1604c8647e559cc5908c17edcfb43c180cc80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - networkx
    - python >=3.7

test:
  imports:
    - matplotx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/matplotx
  summary: Extensions for Matplotlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
