{% set name = "matplotx" %}
{% set version = "0.3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matplotx-{{ version }}.tar.gz
  sha256: a003f9a2e463720ced8062fac543d0087c6c2beedc75072679841c68bd8471a6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit-core
    - python >=3.7
    - matplotlib
  run:
    - matplotlib
    - networkx
    - python >=3.7

test:
  imports:
    - matplotx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nschloe/matplotx
  summary: Extensions for Matplotlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
